spring.application.name=notifications

server.port=8081

# MongoDB Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://root:secretpassword@mongodb:27017/notifications?authSource=admin}

#RabbitMQ Configuration
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT:5672}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:user}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:password}
spring.rabbitmq.listener.simple.default-requeue-rejected=false
