spring.application.name=notifications

server.port=8081

# MongoDB Configuration
spring.mongodb.uri=mongodb://root:secretpassword@localhost:27017/notifications?authSource=admin

#RabbitMQ Configuration
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password